Fix highly likely errors in highly non-projective examples
UniversalDependencies/UD_Danish pull request #18
Opened 2024-02-08 10:22 UTC by KennethEnevoldsen

2024-02-08 12:51 UTC, martinpopel commented on da_ddt-ud-dev.conllu
> +22	.	.	PUNCT	_	_	3	punct	_	_.
Why the final dot? Do you use validate.py before making a PR?

2024-02-08 13:10 UTC, KennethEnevoldsen commented on da_ddt-ud-dev.conllu
> +22	.	.	PUNCT	_	_	3	punct	_	_.
I do not. Is that something which exist somewhere?

2024-02-08 13:10 UTC, KennethEnevoldsen commented on da_ddt-ud-dev.conllu
> +22	.	.	PUNCT	_	_	3	punct	_	_.
(removed the dot)

2024-02-08 13:18 UTC, martinpopel commented on da_ddt-ud-dev.conllu
> +22	.	.	PUNCT	_	_	3	punct	_	_.
See https://universaldependencies.org/release_checklist.html#validation
While `validate.py` would not discover this typo, it is highly recommended to be used especially when editing conllu file manually.

2024-02-08 13:28 UTC, KennethEnevoldsen commented on da_ddt-ud-dev.conllu
> +22	.	.	PUNCT	_	_	3	punct	_	_.
Ahh right. Thanks for letting me know. @dan-zeman can I add this as a GitHub action to the repo?

2024-02-08 22:49 UTC, dan-zeman requested changes

2024-02-08 22:49 UTC, dan-zeman commented on eval.log
This file should not appear in the dev branch, it would make it invalid. The fact that the PR contains my own commits makes me believe that it was wrongly based on the master branch. Instead, it should be based on dev (and directed to dev, too, of course).

2024-02-08 22:49 UTC, dan-zeman commented on da_ddt-ud-train.conllu
This file (change) seems OK to me.

2024-02-08 22:49 UTC, dan-zeman commented on da_ddt-ud-dev.conllu
OK

2024-02-08 22:55 UTC, dan-zeman commented on da_ddt-ud-dev.conllu
> +22	.	.	PUNCT	_	_	3	punct	_	_.
> Ahh right. Thanks for letting me know. @dan-zeman can I add this as a GitHub action to the repo?

The "can I" is ambiguous :-) If you are asking whether I am fine with it, I am. If you are asking whether your account has the right priviledges, I don't know - just try and we'll see. Finally, "can I" could refer to your ability/knowledge how to do it :-) but I suppose you know the answer. I'd actually love to have this in every repo, mailing people who commit something that makes the data invalid, but I never had time to learn how to do it.

2024-02-09 08:41 UTC, KennethEnevoldsen commented on eval.log
Will redo the changes from the main branch then

2024-02-09 08:46 UTC, dan-zeman commented on eval.log
The "main" branch in this case is the `dev` branch :-)
Thanks!

2024-02-09 09:32 UTC, KennethEnevoldsen commented
Moved to #19

2024-02-09 09:32 UTC, closed without merging